name: Release
on:
  release:
  push:
    branches:
      - chandler/configure-cicd

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
      - name: Enable corepack
        run: corepack enable
      - name: Install
        run: yarn install --immutable
      - name: build
        run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
